### ISSUE TITLE
Prep/consider expansion to Contra Costa

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#235]
**BLUF:** We would expand to Contra Costa (CC) to learn about application bottlenecks in another county (aka build the [funnel](https://public.ducksboard.com/NsoSQbe655DQ0DlvQxr6/)) and compare them to SF. Common bottlenecks suggests product/feature opportunities. Disparate bottlenecks suggest there's something important to know but we might not have the hammer (business process interventions, policy interventions, etc.)

**Table stakes** (aka what we need to move forward)
- CC sets up email address to receive Clean apps and clears all incoming cases at least daily
- CC covers ~2 days/week for someone to do Clean application tracking
- CC specifies basic business process for how Clean applications are going to get Cleared > scheduled > interviewed > approved/denied.
- Vakil intros us to ~3 intermediaries who would be active users (probably food bank and other groups currently doing screening + referral or application assistance) so we can talk to them on the phone.

@dave can you review the goals + table stakes above? Does this capture what we want to learn and what we need to say yes?

@RebeccaCoelius can you sanity check the rationale above for expanding clean to Contra Costa? Anything obvious we're not considering?

**Notes from first convo with Vakil**
- Vakil retired as CIO of SF HSA who was our city partner in 2013. He's now doing some consulting work with CC and others to figure out more scalable outreach models.
- The first model he's trying in CC is to move the food bank away from direct application assistance and towards supporting others (other CBOs + volunteers) to do application assistance.
- CC has ~58% participation now and targeted 75% over next two years, which means adding an ~10-14k cases (depending on churn/drop rate)
- CC has 2 units of EWs (~10 total) who do outreach and support CBOs. CBOs call this unit directly to get support on their cases and Clean apps would likely go directly to this group.
- There's a "CalFresh Partners" meeting where all county stakeholders come together and share stats...this would be good place to start.

**Next steps**
- Send table stakes to Vakil (once @daguar confirms)
- Vakil would secure table stakes and probably pull me into a couple phone calls
- Vakil and I probably offer Clean to food bank + folks at the next CalFresh Partners meeting

**Comment by daguar** [comment]
Overall, :+1:, but a few notes:

- I'd like to lay out explicitly (and set timeline for) new features expanding to CC requires *before* moving ahead with this. At a minimum we're talking about:
 - New Heroku instance
 - Some changes to where SF is hard-coded, and abstracting out the case tracking link in email
- I think this is a good opportunity to test out what *minimal business process change* looks like. I say we "let it flow, but instrument" — meaning, let's make the _only_ business change as it relates to actually processing the applications be adding an email address that gets checked and processed, *but* let's use our internal relationship here to *measure* where it fails (and fix it for those clients). *The goal here: to learn what will go wrong if a county does nothing else besides adding an e-mail address.*
- I thought CC might use C4 (instead of MyBenefitsCalWin [MBCW]) and so we'd be able to test out how our process works in C4 counties, but it turns out that CC uses MBCW, so not too much new to learn there.
- Some other specific comments:

> CC covers ~2 days/week for someone to do Clean application tracking

Gut check: is this the level of effort? Feels like it could be high, but I may be wrong and you have a better finger on the pulse.

> Vakil intros us to ~3 intermediaries who would be active users (probably food bank and other groups currently doing screening + referral or application assistance) so we can talk to them on the phone.

I think it's worth going out there for a day and meeting with all these folks (assistors + internal agency folks). It's not far and would be just the right thing to do for county # 2.

**Comment by daguar** [comment]
Some thoughts I put in Slack:

A few of my thoughts re expanding Clean to Contra Costa:

## Goals

1. Main goal is to **test our current hypothesized scaling model**: specifically, if an agency does *nothing more* than add an email address accepting password-protected applications, will the existing business processes handle it?

2. 2nd goal is to **control for SF-specific variables**: we have no clue how much of SF HSA's internal processes (and clients' failure points) are similar to the rest of CA. This is the first step to learning what things are _generally how counties do it_ vs. _just how SF does it_.

3. We **instrument the biz process both for above learning goals but ALSO to ensure all clients through our system succeed, despite potential failure**: that's the main justification for staff time, IMHO. 

## Arguments for Contra Costa as the 2nd county

1. To scale responsibly, the 2nd county needs the higher level of buy-in to instrument biz process (to learn about funnel + make sure all eligible approved) —— we have that in Contra Costa but nowhere else yet (except maybe Solano). It's an opportunistic call.

2. Intuition — SF is more _dissimilar_ to other counties in CA than it is similar. Contra Costa is just straight-up more like the avg county.

3. CA counties basically have 3 types — urban coastal, rural central CA, and LA. Eventually we want to understand the rural+LA, but for now let's make sure we understand urban coastal.

4. It's close — so we can have more personal relationship.

**Comment by alanjosephwilliams** [comment]
In the comment above you state the CC's participation rate is ~58%, with a future target of 75%. In the spreadsheet produced by Diana with ACS data, the adjusted participation rate point estimate is ~85% (SF's is 49% by comparison). Is there something that needs be resolved there, or should we use a particular dataset for these discussions?

I definitely think that Contra Costa serves as a decent proxy for exurban counties, which characterizes a substantial segment of California counties. They are going to have a different ecosystem based on that characterization—different population types, different mobility needs, fewer institutions with well established track records of service delivery and assistance.

I'd also like to get explicit here about what features we think will be required (and timeline for those features, h/t @daguar). It sounds like a lot of that is just going from 1 client to two, abstracting away hard-coded things here and there—and almost nothing user facing.
