### ISSUE TITLE
copy audit

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/clean#298]
We have many user experience improvements under consideration for the next sprint or two. An audit of all copy, mapped against the user's journey through the broader CalFresh application process, is a great place to start. In about an hour we should be able to conduct the audit and identify improvements to include in the frontend dev work that lies ahead.

**Comment by lippytak** [comment]
404/500 pages:
- Let's use our sales phone # (in Twilio health-misc) in addition to or instead of health-lab@. We shouldn't depend on email for time sensitive stuff.
- Let's include the suggested subject/body in the food@sfgov mailto link
- I'd recommend we don't specify 'via Clean' in the email to food@sfgov because the folks on the other end probably won't know about Clean

**Comment by lippytak** [comment]
Homepage:
- Let's either define or not use 'HSA' acronym
- The benefit amount is up to $200 per person
- Let's not use "prove your need" because lots of people who qualify don't think they "need" it. Food Bank really strongly avoids 'need' language. CalFresh is about making families/communities healthier.

**Comment by alanjosephwilliams** [comment]
Big thumbs up. Let's document feedback for every page here.

On Sun, Feb 8, 2015 at 11:03 AM, Jake Solomon <notifications@github.com>
wrote:

> Homepage:
>
>    - Let's either define or not use 'HSA' acronym
>    - The benefit amount is up to $200 per person
>    - Let's not use "prove your need" because lots of people who qualify
>    don't think they "need" it. Food Bank really strongly avoids 'need'
>    language. CalFresh is about making families/communities healthier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/298#issuecomment-73425554>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
I'm closing, because it appears that #307 closed this but @alanjosephwilliams please give a quick look and let me know if this should remain open.

**Comment by alanjosephwilliams** [comment]
:+1: we have new issue for this work.

On Mon, Feb 16, 2015 at 11:26 PM, Dave Guarino <notifications@github.com>
wrote:

> I'm closing, because it appears that #307
> <https://github.com/codeforamerica/clean/pull/307> closed this but
> @alanjosephwilliams <https://github.com/alanjosephwilliams> please give a
> quick look and let me know if this should remain open.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/298#issuecomment-74627281>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
