### ISSUE TITLE
Info sharing: Add agreement to every application

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#324]
I believe we'll need to add the signature on here, as well.

**Comment by lippytak** [comment]
I thought I had a copy but I don't. I pinged Liliana + Carissa and will copy here.

**Comment by lippytak** [comment]
See my proposal below. @daguar + @alanjosephwilliams am I missing any info here that we'll need from HSA? I'm comfortable moving forward on this but will also sanity check with CDSS + CfA lawyers soon.

> Subject: Authorization for release of information
To: San Francisco Human Services Agency

> I, [APPLICANT NAME], authorize you to release the following information regarding my CalFresh application or active case to Code for America:
- Case number
- Current and past application status
- Dates and reasons for all changes to the application status
- Current and past benefit allotment
- Reasons my case was pended or denied
- Description of all verification documents that were

> Code for America will use this information to make sure my case is processed properly.

> [SIGNATURE]
[DATE]
[DOB]
[CASE NUMBER optional/if available]

**Comment by daguar** [comment]
We'll use the Prawn library ( https://github.com/prawnpdf/prawn ) to simply generate this from text, rather than create a form and fill it in.

For the MVP this won't be pretty, but can improve as we go along.

**Comment by daguar** [comment]
Do we want to put the info release form at the beginning or end?

**Comment by lippytak** [comment]
End.

**Comment by lippytak** [comment]
Let's add CfAs HQ info at the end:
> Code for America
155 9th Street, San Francisco 94103
(415) 625-9633
www.codeforamerica.org

**Comment by alanjosephwilliams** [comment]
time for a footer, it seems.

**Comment by daguar** [comment]
Removing the "Case number" area since we don't have it and won't for a while.

**Comment by daguar** [comment]
- I added the name below the signature
- Rebased the working branch against the current master (so it now has the copy audit PR with flow changes)

**Comment by daguar** [comment]
Here's a screenshot of what (I think) is a sufficient MVP version of this feature, currently implemented on a branch:

![screen shot 2015-02-23 at 4 12 58 pm](https://cloud.githubusercontent.com/assets/994938/6338788/f9699648-bb76-11e4-8ee0-1ed92b4d8b2f.png)

It's currently done using the Ruby Prawn library for making PDFs — so it's not a custom-designed form that we're filling in right now; it's done programmatically like:

```ruby
pdf.text "Here is some text"
pdf.image "/path/to/image.png"
pdf.render_file "/path/to/mypdf.pdf"
```

I think v2 of this would be a nicely-designed version, but since it'd involve a semi-significant LOE, this feels right to me for v1.

@alanjosephwilliams @lippytak Does this work for MVP? I think so, but if there are any high-ROI design changes that can be made while staying inside Prawn's capabilities (ie, not requiring changing the code base to fill out a custom PDF form we create), those would make a lot of sense to me.

**Comment by lippytak** [comment]
Looks great to me. The beginning of a game changer :+1:

**Comment by alanjosephwilliams** [comment]
I don't think any design improvements will be high ROI. I'm stoked for v1.
Let's see what we uconver when its out in the wild.

On Mon, Feb 23, 2015 at 2:28 PM, Jake Solomon <notifications@github.com>
wrote:

> Looks great to me. The beginning of a game changer [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/324#issuecomment-75651396>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Awesome — this is complete on the add-info-sharing-agreement-release branch.

I think adding this is pending the completion of the UI ( #323 ) and case tracking business process ( #325 ) — can someone confirm or tell me this isn't the case?

**Comment by daguar** [comment]
Talking with @lippytak, sounds like business process is not a blocker but UI is; as a corollary, saving client application data in the backend ( #321 ) is also a prerequisite for this to actually add value, so that will be my top priority right now.
