### ISSUE TITLE
Copy audit

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#343]
Currently under bullet 1 on the front page, we say: 

> ...If you have documents on hand, you can send them in with your application.

Should we tweak this given our current move to having assistors email these in for now? I'd propose:

> ...If you have documents on hand, we will tell you how to send them in.

or something like that.

**Comment by lippytak** [comment]
Changing to a full copy audit!

**Comment by lippytak** [comment]
- Household stuff. Don't forget it! Came up again today and RM keeps seeing it.

**Comment by lippytak** [comment]
What is "nutrition assistance"? Suggest something like "extra money for groceries"

**Comment by lippytak** [comment]
General
- Pick common pronoun for "we" or "the County" or "HSA"

Home
- Apply for CalFresh in San Francisco, CA > drop CA
- "You may be eligible for hundreds of dollars in food assistance"
  - what is food assistance? hundreds of dollars could be misleading (Food bank feels strongly about this)
  - maybe HEAD = Apply for CalFresh in SF, subhead = "Get extra money for groceries"
- Submit > Apply
- Shorten the steps
  - 1: Apply for CalFresh online right now in 10 minutes.
  - 2: The County (pick a word...) will call you within 10 days for your phone interview.
  - Consider changing to "Get your benefits"? Unclear how many apps require more docs at this point.

Keep going
- "Name is required to apply" > remove passive voice on here and other errors, too
- "This information is required to uniquely identify you in our system." > "The County needs this in order to..." Let's also try to figure out a better way to communicate the reason but I can't think of anything right now.
- "When do you prefer your interview?" > "When should the County call you for your interview?"
  - Make the rest a bit more direct too
- Household
  - H1 maybe "Does anyone else live with you?"
  - H2 maybe "Only include people that you usually buy and cook food with, like children or other family members. You don't need to include roommates or friends if you don't usually share food."
- Drop "Last page..."  b/c it's covered in the checkbox
- Drop "Check to agree" 
- "After you submit, you'll have the chance to provide documents regarding you identification, income, expenses and other relevant information." > "After you submit, you can send in your other documents."

**Comment by alanjosephwilliams** [comment]
This will be closed by #358
