### ISSUE TITLE
Replace 3-page PDF with full 10-page PDF?

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#350]
In #289, we benchmarked the 3-page PDF against the 10-page PDF and found:

- 3-pager = ~7 seconds
- 10-pager = ~9 seconds

Given that it's not a huge difference, I propose we go ahead and start submitting the full 10-page PDF.

I think the cost/benefit for the user works out:
- *Benefit*: we've already seen EWs be confused by minimal 3-page application; a full 10-page one may address these concerns and is super low effort (already done in fact!)
- *Cost*: waiting an additional 2 seconds, but 

What's more, if we're really worried about this long wait-time for the user, we should move this process to a background job. Because that's a separate concern (and this smaller improvement can be implemented immediately with positive net benefit to the user), I've opened a separate issue for it in #349.

**Comment by daguar** [comment]
@lippytak + @alanjosephwilliams — This is fully implemented with automated and manual testing done on the `replace-3page-pdf-with-10page-pdf` branch.

So if both of you give me the greenlight, I'll go ahead and issue the PR.

**Comment by lippytak** [comment]
Let's hold on this for now because it creates more work internally (they print everything out) and I think we can address this more effectively with a simple cover page stating what this application is and alerting EWs that it is a complete application: https://github.com/codeforamerica/clean/issues/112. I suspect more blank pages won't solve the problem (still looks "incomplete" just in a different way ) or create others. If the issue comes up again after we have a cover page then we'll reconsider it.
