### ISSUE TITLE
Test 'engagement' for minimal info apps throughout CA (~20 apps)

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#483]
**Basic idea** is to concierge some minimal info applications throughout CA (0 county dependency) to see how the approach generalizes outside SF:
1. Ads
2. > Collect minimal viable application data (via Typeform or Clean or something else)
3. > Submit application for client via SAWS
4. > 10/30 day client FU

**Goal:**
- Assess the 'engagement' part of the funnel - aka get rough estimate of approval rate via the minimal viable application approach outside of SF
- Get qualitative understanding of bottlenecks via client FU + interview
- See if this approach is feasible at scale

**To do**
- [x] Setup/run ads (probably just pick best performing ad group from the testing in #479 )
- [x] Build the Typeform/survey
  - [x] Should at least include minimal viable app info, FU consent, contact info, and the legalese
  - [x] Confirm minimal viable app info for all 3 SAWS systems (logging in [this google doc](https://docs.google.com/a/codeforamerica.org/spreadsheets/d/1CNC3dC6iouxbf7l3YaM57EQWCCQAoSWz_-_r0w4lw_M/edit#gid=0))
  - [x] Consider minimal screening (SSI?) depending on results from #479 
  - [x] Consider what to do about verification docs, if anything (decision: nothing)
  - [x] Consider if/how to do confirmation page/email/text (just a page, no email/text)
  - [x] QA it
  - [x] Fix review screen
  - [x] More info for AR
  - [x] Make it work for 6+ HH members
  - [x] Sign = full legal name
  - [x] @alanjosephwilliams copy review/audit
  - [x] Consider/decide on AR process
  - [x] Consider asking for full savings + rent/utilities to get better coverage of ES eligibility
- [x] Test application concierging
  - [x] Can all SAWS submit docs? Submit docs later?
  - [x] Get CBO account for C4
  - [x] Get CBO account for MBCW
  - [ ] Get CBO account for LEADER (not a blocker)
  - [x] Fill out the typeform all the way through ourselves and see if we have enough info for all 3 SAWS
  - [x] Get Typeform on getcalfresh.com
  - [x] Incorporate dave feedback
  - [x] Test that we don't accidentally jump over AR/Sig
- [ ] Check feasibility of scaling this via automation on each SAWS system (cc @daguar )
  - [ ] C4
  - [ ] MBCW
  - [ ] LEADER
- [x] Setup FU/data tracking (remember the goal!)
  - [x] ZenDesk SMS alerts so we can submit applications quickly
  - [x] Make template spreadsheet for final outcome data
  - [x] Setup custom fields in ZenDesk to capture all the data we need
  - [ ] Template follow up via email/mms/voice. Email survey template + Textit.in FLOW that we would start.
  - [x] Automate ticket / FU creation
  - [x] Consider ZenDesk/SMS integration for folks who want a text FU (No need to automate given small volume)
  - [x] Qualitative phone interviews with who? How to track? Payment?
  - [x] Figure out how we're going to reliably get case data? Depends on a lot of things... (decision = 2 client FUs + AR)

**Comment by lippytak** [comment]
^ sketched out with more of a plan that I'd love to review with @alanjosephwilliams and @daguar soon!

**Comment by lippytak** [comment]
Can integrate Zendesk + Survey monkey to send survey for the FU

**Comment by lippytak** [comment]
Got C4 CBO account. MBCW on the way.

Confirmed C4 cannot accept verification documents.

**Comment by lippytak** [comment]
LEADER *DOES* allow verification upload:
![screen shot 2015-04-15 at 11 48 46 am](https://cloud.githubusercontent.com/assets/2533112/7166847/71e2cd54-e365-11e4-8dc9-9c1864d17d64.png)

However, the Food Bank CFO team recommends against it. "The County is having trouble opening those attachments. I recommend you drop them off in-person." Wow...

**Comment by lippytak** [comment]
CBO acct for MBCW :+1:

Check the Health Private Credentials doc.

**Comment by lippytak** [comment]
Logging minimal required questions per system here: https://docs.google.com/a/codeforamerica.org/spreadsheets/d/1CNC3dC6iouxbf7l3YaM57EQWCCQAoSWz_-_r0w4lw_M/edit#gid=0

**Comment by lippytak** [comment]
MBCW has (at least sometimes) a CAPTCHA:
![screen shot 2015-04-15 at 12 24 56 pm](https://cloud.githubusercontent.com/assets/2533112/7167514/784b2dc6-e36a-11e4-8dc6-d0818f6ff2e9.png)

This was on the individual app, not via the CBO portal.

**Comment by lippytak** [comment]
Looks like LEADER has something like a CBO account:
![leader cbo account](https://cloud.githubusercontent.com/assets/2533112/7169367/a347478a-e379-11e4-8dca-e5cfec878ab2.png)

I emailed Estelle and Frank who I found on the internet that seem to work for DPSS CalFresh.

**Comment by lippytak** [comment]
Some notes on the Typeform
- SSI, student, non-citizen will branch to an informational page but not screen people out
- Income we'll just present as a table image + 'do you want to continue'
- Contact preference/info
- Legalese for AR
- Confirmation

**Comment by alanjosephwilliams** [comment]
:+1: :+1: :+1:

On Wed, Apr 15, 2015 at 3:26 PM, Jake Solomon <notifications@github.com>
wrote:

> Some notes on the Typeform
>
>    - SSI, student, non-citizen will branch to an informational page but
>    not screen people out
>    - Income we'll just present as a table image + 'do you want to
>    continue'
>    - Contact preference/info
>    - Legalese for AR
>    - Confirmation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/483#issuecomment-93574111>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
Won't be able to get a LEADER CBO account in time but we'll start the test without it - not a blocker just a nice-to-have.

**Comment by lippytak** [comment]
Zendesk views setup
![screen shot 2015-04-16 at 10 40 13 am](https://cloud.githubusercontent.com/assets/2533112/7187395/00a7a3b0-e425-11e4-8860-253700339147.png)

**Comment by alanjosephwilliams** [comment]
GetCalFresh.com QA results early afternoon 4/16:
- Title of the page is currently "CalFresh concierge test"
- On the main page subhead, I like "California program that provides" rather than "gives you"
- Asterisk denoting required is nice.
- Are we going to have issues with address formatting?
- What if someone is homeless? SOL? I know that's not who we are targeting, so maybe.
- I had to look up my ZIP code.
- It would be nice if we could use real bullet points on the list.
- Also on SSI, we should break the copy into two sentences, on two lines.
- Why no link to more information on the Citizenship warning?
- It would be nice if our "skip this part" could be in a different color....
- I might not know a household member's social security number (right now we only speak to them actually not having one).
- I was asked about income before the chart....maybe that's good, avoids people anchoring under the threshold or not being accurate.
- I actually think the chart works. It's a little weird that we don't address the savings part in the copy though.
- I got "Good News, it looks like you might be eligible" after saying that yes, I have SSI and yes, I am a full time student. I understand that is our approach—give people exits instead of giving intelligent determinations, but I'm just narrating here.
- Love the "how can we get in touch" copy.
- Love that we show the information to people to confirm it is accurate. I think that we should actually tell people _how_ they can go back though. Specifically by using the two arrow buttons in the bottom right hand.
- Welp, there is my photo. Is it weird that there is no information about me other than my first name? I think "Will be able to access and check on the status of your case. This allows us to give you important and timely information." would be less intense. I also think we could end with something more reassuring, like "He will have no right _or ability_ to spend your CalFresh benefits." Do we need an asterisk here about where they can learn more about authorized representation? Or who we are?
- Maybe we should include a congratulations message and graphic explaining the next step before we go to the final button?
- Ah I see, it came right after :)
- I would love to see us give people on off-ramp to somewhere else useful. Maybe something like "Need food immediately? Find a food pantry near you."

**Comment by alanjosephwilliams** [comment]
A quick note on workflow for customer satisfaction/client follow up surveys sent via Zendesk/email:
- Check the 10dayFU view
- For each new ticket that has not already been contacted:
   - Edit the title of the ticket to reflect the e-mail subject line we want to see.
   - Delete or reformat the details of their case so it doesn't appear awkward.

**Comment by alanjosephwilliams** [comment]
Changes made. A graphic for the last page would be a big improvement.

**Comment by lippytak** [comment]
Template spreadsheet for outcomes: https://docs.google.com/a/codeforamerica.org/spreadsheets/d/1vfjxik5oYBRnm4ssXVoR5H7aYwuNWLbUr2yqIRp8fZU/edit#gid=978867673

**Comment by lippytak** [comment]
ZenDesk view + SMS alert both working:
![screen shot 2015-04-17 at 5 29 19 am](https://cloud.githubusercontent.com/assets/2533112/7201985/b82e8484-e4c2-11e4-8432-211b73f95f0f.png)

![screen shot 2015-04-17 at 5 29 14 am](https://cloud.githubusercontent.com/assets/2533112/7201986/bb40f94a-e4c2-11e4-991f-277bad79a0eb.png)

**Comment by lippytak** [comment]
It is quite painful to fill out MBCW because you can't copy-paste into any fields. This is HIGHLY error prone. We need to be really careful about not making typos at all.

**Comment by lippytak** [comment]
@daguar ^ may have automation implications

**Comment by lippytak** [comment]
MBCW AR:
- "If you are an Authorized Representative you will need to give the County proof of identity for yourself and the applicant."
- Only name required so no risk of accidental phone contact to AR instead of client :+1: 
![mbcw-ar](https://cloud.githubusercontent.com/assets/2533112/7202097/de5f98b8-e4c3-11e4-8708-1474890d19cb.png)

**Comment by lippytak** [comment]
MBCW has an 'i don't know SSN' box for other HH members :+1:

**Comment by lippytak** [comment]
Just took our TypeForm and then used that info to populate complete applications on all 3 SAWS. Some notes:

MBCW: 
- Requires 'how is this person related to you' for other HH members. I'm mixed on whether we should just select 'not related' or add the question.
- Best strategy: Go to 28% (after adding HH members) > then click back to start > 'next' your way to the first e-sig screen at 32% > submit

C4:
- Make sure to check interview pref on 'Your info' page
- Living situation IS required (in home, temporarily out, permanently out). Relationship is NOT.
- Make sure to fill out income / savings if ES eligible because it doesn't ask the questions explicitly
- 'Creating an e-sig' flow is ridiculously confusing. We have to create meta-accounts just for signatures where each individual has a username/PIN. I vote we just sign as the AR each time and don't create an account for the client.

LEADER:
- Remember 'best way to contact you'
- Requires 'living situation' per HH member (not relationship). Let's just default to 'living in the home'.
- AR on first screen - only requires name.
- Confirmed you can submit multiple CalFresh apps under one regular LEADER account :thumbs:

**Comment by lippytak** [comment]
Decided to ask 3 questions for ES:
1. what was your income in the last 30 days?
2. do you have less than $100 in savings?
3. how much do you spend on rent/utilities every month?

So we will miss cases where savings is >$100 but (income + savings ) < rent/utilities.

**Comment by lippytak** [comment]
Let's try AR like this:
- Only AR WITHOUT benefit access
- Only include name so there's no risk of accidentally contacting us instead of client
- Only use AR if we don't get client response on FU
- Give good faith effort to remove ourselves from AR after the 30 days

**Comment by lippytak** [comment]
- Phone interview notes will live here: https://github.com/codeforamerica/clean/wiki/Phone-interviews-with-engagement-test-group
- Tracking Interviews + payments in ZenDesk: 
![screen shot 2015-04-17 at 6 59 13 am](https://cloud.githubusercontent.com/assets/2533112/7203409/4df82b94-e4cf-11e4-801f-8b595e122c32.png)

- @alanjosephwilliams could you link to a private spreadsheet here that has all of our Amazon codes so we don't give out duplicates?

**Comment by lippytak** [comment]
- Adwords setup (paused): 2 campaigns at $50/day each taking best performing Adgroup from the earlier test. One campaign targets CA and the other targets SF to oversample in SF.
- Form up at getcalfresh.com

I'd like a quick review/sanity check of everything @daguar @alanjosephwilliams then good to go here and we can move to planning FU process.

**Comment by daguar** [comment]
QA feedback:


Address — might want to expand title ("home address and city") or check for zip code because if I'm going through quick I might just put my street address
	
"When were you born?" --> why not "Date of birth?"

"Are you a US citizen?" --> it says "Or do you have a green card?" below. Might be confusing? Maybe say "Are you a legal resident of the US? (a citizen or have a green card)"
	--> separate concerns around people feeling nixed by this and stopping
	--> OR want to make these two separate questions?

SSN: Add comma --> "If you don't have one, just skip this question"
	--> also the add'l household member says "leave this blank" rather than skip — we should keep consistent

"Live in your household" as bolded
	—>  NOT DOING -> why not say "how many people do you buy or cook food with? (this is what CalFresh calls "a household")"?
	—> bold the whole thing

The income thing is weird after asking my income — let's discuss
	--> Copy change with "got it" 

"Looks like you qualify! Just a few more questions" is AWESOME

BUG: went from email to just ending (no AR, no legalese)

"Alan works at a non-profit organization, called Code for America." remove comma

At end, maybe use some bolding at front of each step:
	"Phone Interview: …"
	"Submitting documents: …"

**Comment by lippytak** [comment]
up and running!

**Comment by lippytak** [comment]
Some errors on v1:
- Missing city/zip - Separating it into different required fields now)
- Missing area code - Requiring 10 or more digits and added a note to 'include your area code'

Both fixed now thanks to @alanjosephwilliams for noticing both!

**Comment by lippytak** [comment]
Got 20 apps. Pausing ads now. Ad results:
![screen shot 2015-04-19 at 7 29 07 pm](https://cloud.githubusercontent.com/assets/2533112/7222792/60ee94ac-e6ca-11e4-9654-c34857621fca.png)

**Comment by lippytak** [comment]
Note we've had at least one homeless client who didn't say so here...entered an address they *may* move into soon. This would however meet the CalFresh definition of 'homeless.' Suggests an insecure housing question or something might be valuable.

**Comment by lippytak** [comment]
FU: https://github.com/codeforamerica/clean/issues/491

Feasibility check browser automation: https://github.com/codeforamerica/clean/issues/492
